/*USE FOR CREATE DATABASE, ONLY ONE TIME*/
CREATE DATABASE MUSICA;

USE MUSICA;

CREATE TABLE CANCIONES(
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    GENERO VARCHAR(50),
    AUTOR VARCHAR(50)
);